language: python

python:
  - 3.8

services: postgresql

addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE hasker-db;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic

script:
  - python manage.py test