# Generated by Django 3.0.5 on 2020-05-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0003_auto_20200505_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
