# Generated by Django 3.0.5 on 2020-05-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0006_auto_20200511_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answer_set', to='hasker_app.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
