# Generated by Django 3.0.5 on 2020-05-13 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hasker_app', '0009_auto_20200512_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='answers_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='questions_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
