# Generated by Django 3.0.5 on 2020-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0010_auto_20200513_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='hasker_app.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='pictures/default.jpg', upload_to='pictures/'),
        ),
    ]
