# Generated by Django 3.0.5 on 2020-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0011_auto_20200514_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.TextField(max_length=100),
        ),
    ]
