# Generated by Django 3.0.5 on 2020-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0013_auto_20200515_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
