# Generated by Django 3.0.5 on 2020-05-23 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hasker_app', '0015_auto_20200523_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users_voted',
        ),
        migrations.AddField(
            model_name='question',
            name='users_voted_down',
            field=models.ManyToManyField(blank=True, related_name='questions_voted_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='users_voted_up',
            field=models.ManyToManyField(blank=True, related_name='questions_voted_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
