# Generated by Django 3.0.5 on 2020-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0018_auto_20200530_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default.jpeg', upload_to='pictures/'),
        ),
    ]
