# Generated by Django 3.0.5 on 2020-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0019_auto_20200530_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.STATIC_ROOT/img/default.jpeg', upload_to='pictures/'),
        ),
    ]
