#!/bin/sh

# set -o errexit
# set -o pipefail
# set -o nounset

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${HASKER_DATABASE_NAME}",
        user="${HASKER_DATABASE_USER}",
        password="${HASKER_DATABASE_PASSWORD}",
        host="${HASKER_DATABASE_HOST}",
        port="${HASKER_DATABASE_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"